from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from client import *

class Ui_Register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
       # MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(open('mystyle.css','r').read())
        #MainWindow.showFullScreen()
        MainWindow.showMaximized()
       # MainWindow.showNormal()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(250, 0, 250, -1)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.Orglabel = QtWidgets.QLabel(self.centralwidget)
        self.Orglabel.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Orglabel.setFont(font)
        self.Orglabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Orglabel.setObjectName("Orglabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Orglabel)
        self.OrgEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OrgEdit.setMaximumSize(QtCore.QSize(550, 16777215))
        self.OrgEdit.setObjectName("OrgEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.OrgEdit)
        self.Emaillabel = QtWidgets.QLabel(self.centralwidget)
        self.Emaillabel.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Emaillabel.setFont(font)
        self.Emaillabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Emaillabel.setObjectName("Emaillabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Emaillabel)
        self.EmailEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailEdit.setMaximumSize(QtCore.QSize(550, 16777215))
        self.EmailEdit.setObjectName("EmailEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.EmailEdit)
        self.Namelabel = QtWidgets.QLabel(self.centralwidget)
        self.Namelabel.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Namelabel.setFont(font)
        self.Namelabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Namelabel.setObjectName("Namelabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Namelabel)
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setMaximumSize(QtCore.QSize(550, 16777215))
        self.NameEdit.setObjectName("NameEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.NameEdit)
        self.Passlabel = QtWidgets.QLabel(self.centralwidget)
        self.Passlabel.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Passlabel.setFont(font)
        self.Passlabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Passlabel.setObjectName("Passlabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Passlabel)
        self.PassEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PassEdit.setMaximumSize(QtCore.QSize(550, 16777215))
        self.PassEdit.setObjectName("PassEdit")
        self.PassEdit.setEchoMode(QLineEdit.Password)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.PassEdit)
        self.RegButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegButton.setMaximumSize(QtCore.QSize(550, 16777215))
        self.RegButton.setObjectName("RegButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.RegButton)
        self.Titlelabel = QtWidgets.QLabel(self.centralwidget)
        self.Titlelabel.setMaximumSize(QtCore.QSize(550, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Titlelabel.setFont(font)
        self.Titlelabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.Titlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlelabel.setObjectName("Titlelabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Titlelabel)
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setMaximumSize(QtCore.QSize(550, 16777215))
        self.LoginButton.setObjectName("LoginButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LoginButton)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        
        self.RegButton.clicked.connect(self.RegisterWrapper)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)     
        
    def RegisterWrapper(self):
      #print "we are in Reg Warpper"
      self.client=client('http://18.213.123.42',3500)
      self.name=self.NameEdit.text()
      self.email=self.EmailEdit.text()
      self.password=self.PassEdit.text()
      self.org=self.OrgEdit.text()
      #print("user :"+self.name+"\nemail :"+self.email+"\npassword :"+self.password+"\norg :"+self.org)
      self.msg,self.status=self.client.register(self.name,self.email,self.password,self.org)
      #print(self.status)
      self.customResMsg(self.status,self.msg)
    #@override
    def customResMsg(self,status,msg):
        if(status == 200) :
           QtWidgets.QMessageBox.information(self.centralwidget, "Registered!", msg)
        elif(status == 408) :
          QtWidgets.QMessageBox.critical(self.centralwidget, "Connection Error", msg)
        elif(status == 500 and "unique" in msg) :
          QtWidgets.QMessageBox.warning(self.centralwidget, "User Already Exists", msg)
        elif(status == 500 and "required" in msg) :
          QtWidgets.QMessageBox.critical(self.centralwidget, "Missing Parameter", msg)
          
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registeration"))
        self.Titlelabel.setText(_translate("MainWindow", "Create an account"))
        self.Namelabel.setText(_translate("MainWindow", "Name"))
        self.Emaillabel.setText(_translate("MainWindow", "Email"))
        self.Passlabel.setText(_translate("MainWindow", "Password"))
        self.Orglabel.setText(_translate("MainWindow", "Organization"))
        self.RegButton.setText(_translate("MainWindow", "Register"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))